
export const TRANS_RECOM_START = 'TRANS_RECOM_START';
export const TRANS_RECOM_SUCCESS = 'TRANS_RECOM_SUCCESS';
export const TRANS_RECOM_FAILED = 'TRANS_RECOM_FAILED';

export const TRANS_BITCOIN_START = 'TRANS_BITCOIN_START';
export const TRANS_BITCOIN_SUCCESS = 'TRANS_BITCOIN_SUCCESS';
export const TRANS_BITCOIN_FAILED = 'TRANS_BITCOIN_FAILED';

export const TRANS_BITFINEX_START = 'TRANS_BITFINEX_START';
export const TRANS_BITFINEX_SUCCESS = 'TRANS_BITFINEX_SUCCESS';
export const TRANS_BITFINEX_FAILED = 'TRANS_BITFINEX_FAILED';